[project]
name = "convert-images-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arrow>=1.3.0",
    "pillow>=11.0.0",
    "pillow-avif-plugin>=1.4.6",
]
